---
deployment:
  tasks:
    # Définir le chemin de déploiement
    - export DEPLOYPATH=/home/username/public_html/
    
    # Copier uniquement le contenu du dossier dist/ (pré-buildé)
    - /bin/cp -R dist/* $DEPLOYPATH
    
    # Définir les permissions correctes pour les dossiers
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    
    # Définir les permissions correctes pour tous les fichiers
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    
    # Permissions spécifiques
    - /bin/chmod 644 $DEPLOYPATH/index.html
    - /bin/chmod 755 $DEPLOYPATH
